small improvements, while working on tf-sandbox

diff --git a/lib/terragrunt/terragrunt-noninteractive b/lib/terragrunt/terragrunt-noninteractive
--- a/lib/terragrunt/terragrunt-noninteractive
+++ b/lib/terragrunt/terragrunt-noninteractive
@@ -5,11 +5,27 @@
 # change between CI and local commands.
 set -euo pipefail
 
+sed_norm_log() {
+  # remove distracting output from terragrunt logs
+  sed "
+  # shorten $PWD to .
+  s#$PWD\>#.#
+  s#$HOME\>#\$HOME#
+  s#$HOME\>#\$HOME#
+  # remove ./ from 'terragrunt module prefix'
+  s#^\[\./#[#
+  # remove unecessary '.' terragrunt module prefix
+  s#^\[\.\] ##
+"
+}
+
 ## Terragrunt
-export TERRAGRUNT_NON_INTERACTIVE=true
-# configured in tacos-gha.demo/terraform/terragrunt-base.hcl
-# TODO: auto-configure terragrunt retry patterns in tacos-gha
-export TERRAGRUNT_NO_AUTO_RETRY=false
+if ! tty-exists; then
+  export TERRAGRUNT_NON_INTERACTIVE=true
+  # configured in tacos-gha.demo/terraform/terragrunt-base.hcl
+  # TODO: auto-configure terragrunt retry patterns in tacos-gha
+  export TERRAGRUNT_NO_AUTO_RETRY=false
+fi
 # this is necessary for recursive init
 export TERRAGRUNT_NO_AUTO_INIT=false
 # these should *all* be IAC'd
@@ -48,6 +64,6 @@ done
 # sed: shorten the absurdly long "module prefix", but don't combine stdout/err
 "$TERRAGRUNT" "$@" \
   0</dev/null \
-  1> >( sed "s#$PWD/##g; s#$PWD\>#.#; s#^\[\.\] ##" >&1 ) \
-  2> >( sed "s#$PWD/##g; s#$PWD\>#.#; s#^\[\.\] ##" >&2 ) \
+  1> >( sed_norm_log >&1 ) \
+  2> >( sed_norm_log >&2 ) \
 ;
