Revert "bump stable (#131)"
This reverts commit d52ab90ab5925164ea7115beef07bf800da9f6e5, reversing
changes made to efc19e7fd164d8f7150cd35162d865c406915f47.

issues found:
* tf-lock-acquire fails to init: https://github.com/getsentry/ops/actions/runs/7788464101/job/21237951827?pr=9276
* debug mode crash: https://github.com/getsentry/ops/actions/runs/7788464101/job/21238624841?pr=9276#step:4:4904

diff --git a/lib/ci/tacos-apply b/lib/ci/tacos-apply
--- a/lib/ci/tacos-apply
+++ b/lib/ci/tacos-apply
@@ -2,44 +2,73 @@
 set -euo pipefail
 export TERRAGRUNT_INCLUDE_MODULE_PREFIX=false
 
-refuse() {
-    reason="$1"
-   (
-   echo "### TACOS Apply: $TF_ROOT_MODULE"
-   cat  # pass deeper explanation via stdin
-   echo
-   echo "Apply request refused: $reason"
-EOF
-) | gha-step-summary >/dev/null
-    exit 1
-}
+if ! [[ "$GITHUB_PR_APPROVERS" ]]; then
+    : no approvers! bail.
+    gha-step-summary >/dev/null <<EOF
+### TACOS Apply: $TF_ROOT_MODULE
 
-# NOTE: approval is different than approvers, due to codeowners
-if ! "$GITHUB_PR_APPROVED"; then
-    refuse "PR has no approvals" <<EOF
 Production changes must be peer-reviewed.
 Please try again after code review.
+
+Apply request refused: PR has no approvals
 EOF
+    exit 1
 fi
 
-if "$GITHUB_PR_DRAFT"; then
-    refuse "PR is not Ready" <<EOF
-Draft PRs cannot be applied.
-Please try again after code review.
-EOF
-fi
+cmd=(
+  env GETSENTRY_SAC_VERB=apply
+  sudo-gcp
+  tf-lock
+  terragrunt-noninteractive run-all
+  apply --lock=true --auto-approve
+)
 
-if [[ "$GITHUB_PR_STATE" != "OPEN" ]]; then
-    refuse "PR is not open" <<EOF
-Applies are only allowed for open PRs.
-You may try reopening the PR first.
-EOF
-fi
+tf_log=tf-log.hcl
+console_log=console.log
+with-user-env "$TF_ROOT_MODULE" \
+    "${cmd[@]}" 2>&1 >"$tf_log" |
+  tee "$console_log" \
+  && status=$? \
+  || status=$? \
+;
 
-tf-step-summary \
-  "TACOS Apply" \
-  "$TACOS_GHA_HOME/lib/tacos/apply" \
-  <<EOF
+summary="$(
+  if tac "$tf_log" | grep -E -im1 'complete'; then
+    : :D
+  elif cat "$console_log" "$tf_log" | grep -E -im1 'error'; then
+    : D:
+  else
+    echo "summary failed!($?)"
+  fi
+)"
+
+# TODO: hide "commands" in PR comments when exit code is 0
+# TODO: hide tf-init and tf-refresh outputs from tf log -- run them separate?
+gha-step-summary >/dev/null <<EOF
+### TACOS Apply: $TF_ROOT_MODULE
 
 Approvers: $GITHUB_PR_APPROVERS
+
+<details>
+  <summary>$summary</summary>
+
+  Commands: (exit code: $status)
+
+\`\`\`console
+$(
+  # match `console` syntax highlighting by removing '+ ' from xtrace lines
+  uncolor "$console_log" |
+    sed -r 's/^\++ \$ /\n$ /'
+)
+\`\`\`
+
+  Result:
+
+\`\`\`hcl
+$(cat "$tf_log")
+\`\`\`
+
+</details>
 EOF
+
+exit "$status"
