avoid interleaving output.summary command; refine output

diff --git a/lib/tf_lock/tf-lock-acquire b/lib/tf_lock/tf-lock-acquire
--- a/lib/tf_lock/tf-lock-acquire
+++ b/lib/tf_lock/tf-lock-acquire
@@ -18,13 +18,11 @@ if "$lock"; then
   tf_user="$(whoami)@$(hostname -f)"
   if [[ "$lock_user" == "$tf_user" ]]; then
     # already done!
-    echo >&2 "success: acquired lock (for $lock_user): $root_module"
-    jq .ID <<< "$lock_info"
+    echo >&2 "tf-lock-acquire: success: $root_module($lock_user)"
+    jq -r .ID <<< "$lock_info"
     exit 0
   else
-    cat >&2 <<EOF
-error: lock held: $lock_user (not $tf_user): $root_module
-EOF
+    echo >&2 "tf-lock-acquire: failure: not $tf_user: $root_module($lock_user)"
     exit "$TF_LOCK_EHELD"
   fi
 fi
