Adding check for sum

diff --git a/.github/workflows/selftest-matrix-io.yml b/.github/workflows/selftest-matrix-io.yml
--- a/.github/workflows/selftest-matrix-io.yml
+++ b/.github/workflows/selftest-matrix-io.yml
@@ -12,7 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        key: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
+        key: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
           
     steps:
       - name: Checkout
@@ -42,4 +42,13 @@ jobs:
         shell: bash
         run: |
           cat matrix-fanin.json
+
+          : sum all of the values
+          sum=$(jq -r 'to_entries | map(.value) | add' matrix-fanin.json)
+
+          : check that the sum is 55
+          if [[ $sum -ne 55 ]]; then
+            echo "ERROR: sum is $sum, expected 55"
+            exit 1
+          fi
 
