imported from .demo repo, verbatim

diff --git a/.github/workflows/tacos_unlock.yml b/.github/workflows/tacos_unlock.yml
--- a/.github/workflows/tacos_unlock.yml
+++ b/.github/workflows/tacos_unlock.yml
@@ -15,6 +15,7 @@ env:
   working_dir: "."
   deploy_environ: "dev"
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  GETSENTRY_SAC_VERB: apply
 
 jobs:
   terraform_unlock:
@@ -24,6 +25,8 @@ jobs:
       pull-requests: write
       id-token: write
     if: ${{ github.event.label.name == ':taco::unlock' }}
+    outputs:
+      summary: ${{ steps.release-terraform-lock.outputs.summary }}
     steps:
       - uses: actions/checkout@v4
       - uses: HatsuneMiku3939/direnv-action@v1
@@ -83,17 +86,51 @@ jobs:
           cat <<< "::add-mask::$(gcloud auth print-access-token)"
 
       - name: Release Terraform lock
+        id: release-terraform-lock
         run: |
           # release all tfstate locks currently held
+          # FIXME: surface unexpected unlock failures
           ./lib/terragrunt/slices |
             xargs ./lib/github/log-as-step-summary \
-              sudo-sac ./lib/tf-lock/tf-lock-release \
+              sudo-sac sh -c '
+                for slice in "$@"; do
+                  ./lib/tf-lock/tf-lock-release "$slice" || : unlock failed
+                done
+              ' \
             \
           ;
 
+  summary:
+    name: "Summarize lock state."
+    needs: [terraform_unlock]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Comment on PR regarding lock state
+        uses: actions/github-script@v7
+        env:
+          summary: ${{ needs.terraform_unlock.outputs.summary }}
+        with:
+          script: |
+            const summary = JSON.parse(process.env.summary)
+            const body = `\
+            Terraform lock state:
+
+            ${summary}
+            `
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: body,
+            });
+
+  reset_label:
+    runs-on: ubuntu-latest
+    if: |
+      github.event.label.name == ':taco::unlock'
+    steps:
       - name: Reset label
         uses: actions/github-script@v7
-        if: always()
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
