expose tf-lock commands

diff --git a/.github/workflows/tacos_unlock.yml b/.github/workflows/tacos_unlock.yml
--- a/.github/workflows/tacos_unlock.yml
+++ b/.github/workflows/tacos_unlock.yml
@@ -110,12 +110,12 @@ jobs:
         id: release-terraform-lock
         run: |
           # release all tfstate locks currently held
-          # FIXME: surface unexpected unlock failures
+          # FIXME: matrix strategy, surface unexpected unlock failures
           terragrunt-slices |
             xargs gha-log-as-step-summary \
               sudo-sac sh -c '
                 for slice in "$@"; do
-                  ./tacos-gha/lib/tf-lock/tf-lock-release "$slice" || : unlock failed
+                  tf-lock-release "$slice" || : unlock failed
                 done
               ' \
             \
